
import { LanguageCode, LanguageOption } from '@/types';

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English', nativeLabel: 'English' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்' },
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা' },
  { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी' },
  { code: 'es', label: 'Spanish', nativeLabel: 'Español' },
];

export const UI_TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    appTitle: 'SetuHealth AI Copilot',
    appSubtitle: 'Bridging Medical Jargon to Human Understanding',
    tabOverview: 'Dashboard Overview',
    tabUpload: 'Scan & Analyze Record',
    tabTimeline: 'Health Journey Timeline',
    tabTrends: 'Vital Trends & Analytics',
    tabMeds: 'Medication Schedule',
    tabAbdm: 'ABDM / ABHA Digital Hub',
    tabArchitecture: 'Architecture & Diagrams',
    tabDeck: 'Presentation Slides',
    uploadBtn: 'Upload New Medical Record',
    trySampleBtn: 'Try Sample Record',
    analyzingDoc: 'Analyzing document with Medical Vision & OCR...',
    plainSummaryTitle: 'AI Health Summary in Plain Language',
    whyItMatters: 'Why This Matters to Your Health',
    actionPlan: 'Recommended Action Steps',
    dietTips: 'Lifestyle & Dietary Guidance',
    questionsForDoctor: 'Questions to Ask Your Doctor',
    flaggedAbnormal: 'Flagged Biomarkers & Lab Results',
    normal: 'Normal',
    elevated: 'Elevated (High)',
    low: 'Low',
    critical: 'Critical Alert',
    readAloud: 'Read Aloud (Voice)',
    stopReading: 'Stop Reading',
    downloadFhir: 'Download ABDM FHIR R4 (JSON)',
    abhaLinked: 'ABHA Linked & Verified',
    routineCheck: 'Routine Monitoring',
    consultDoctorSoon: 'Consult Doctor Soon',
    immediateCare: 'Immediate Care Advised',
    safetyDisclaimer: 'Medical Disclaimer: SetuHealth AI is an informational and educational assistant. Always verify clinical findings with a certified physician.',
  },
  hi: {
    appTitle: 'सेतु हेल्थ एआई कॉपायलट',
    appSubtitle: 'जटिल मेडिकल रिपोर्ट को आसान हिंदी भाषा में समझें',
    tabOverview: 'डैशबोर्ड अवलोकन',
    tabUpload: 'दस्तावेज़ स्कैन व विश्लेषण',
    tabTimeline: 'स्वास्थ्य यात्रा टाइमलाइन',
    tabTrends: 'वाइटल ट्रेंड्स व विश्लेषण',
    tabMeds: 'दवाइयों का समय-सारणी',
    tabAbdm: 'आयुष्मान भारत (ABDM/ABHA)',
    tabArchitecture: 'सिस्टम आर्किटेक्चर',
    tabDeck: 'प्रस्तुति स्लाइड्स',
    uploadBtn: 'नई मेडिकल रिपोर्ट अपलोड करें',
    trySampleBtn: 'सैंपल रिपोर्ट आज़माएं',
    analyzingDoc: 'मेडिकल विज़न और OCR द्वारा रिपोर्ट पढ़ी जा रही है...',
    plainSummaryTitle: 'सरल भाषा में आपका स्वास्थ्य सारांश',
    whyItMatters: 'यह आपके स्वास्थ्य के लिए क्यों महत्वपूर्ण है',
    actionPlan: 'अनुशंसित कदम और देखभाल',
    dietTips: 'आहार एवं जीवनशैली सुझाव',
    questionsForDoctor: 'अगली बार डॉक्टर से पूछने योग्य सवाल',
    flaggedAbnormal: 'असामान्य या ध्यान देने योग्य जांच परिणाम',
    normal: 'सामान्य (Normal)',
    elevated: 'बढ़ा हुआ (High)',
    low: 'कम (Low)',
    critical: 'अति-गंभीर चेतावनी',
    readAloud: 'बोलकर सुनाएं (आवाज़)',
    stopReading: 'रोकें',
    downloadFhir: 'ABDM FHIR R4 डाउनलोड करें (JSON)',
    abhaLinked: 'ABHA आईडी सत्यापित है',
    routineCheck: 'नियमित निगरानी',
    consultDoctorSoon: 'शीघ्र डॉक्टर से परामर्श लें',
    immediateCare: 'तत्काल चिकित्सीय सलाह लें',
    safetyDisclaimer: 'चिकित्सीय अस्वीकरण: सेतु हेल्थ एआई केवल शैक्षणिक व मार्गदर्शक सहायता के लिए है। किसी भी दवा या उपचार में बदलाव से पहले अपने चिकित्सक से अवश्य मिलें।',
  },
  te: {
    appTitle: 'సేతు హెల్త్ AI కోపైలట్',
    appSubtitle: 'క్లిష్టమైన వైద్య నివేదికలను సులభమైన తెలుగులో అర్థం చేసుకోండి',
    tabOverview: 'డాష్‌బోర్డ్',
    tabUpload: 'రిపోర్ట్ స్కాన్ & విశ్లేషణ',
    tabTimeline: 'ఆరోగ్య టైమ్‌లైన్',
    tabTrends: 'వైటల్ ట్రెండ్స్ & విశ్లేషణ',
    tabMeds: 'మందుల షెడ్యూల్',
    tabAbdm: 'ABDM / ABHA డిజిటల్ హబ్',
    tabArchitecture: 'సిస్టమ్ ఆర్కిటెక్చర్',
    tabDeck: 'ప్రెజెంటేషన్ స్లయిడ్‌లు',
    uploadBtn: 'కొత్త మెడికల్ రికార్డును అప్‌లోడ్ చేయండి',
    trySampleBtn: 'నమూనా రిపోర్ట్ ప్రయత్నించండి',
    analyzingDoc: 'OCR & మెడికల్ విజన్ ద్వారా నివేదిక విశ్లేషించబడుతోంది...',
    plainSummaryTitle: 'సరళమైన భాషలో మీ ఆరోగ్య సారాంశం',
    whyItMatters: 'ఇది మీ ఆరోగ్యానికి ఎందుకు ముఖ్యం',
    actionPlan: 'సిఫార్సు చేయబడిన చర్యలు',
    dietTips: 'ఆహారం మరియు జీవనశైలి సలహాలు',
    questionsForDoctor: 'డాక్టర్‌ను అడగవలసిన ప్రశ్నలు',
    flaggedAbnormal: 'గమనించవలసిన ల్యాబ్ ఫలితాలు',
    normal: 'సాధారణం (Normal)',
    elevated: 'ఎక్కువ (High)',
    low: 'తక్కువ (Low)',
    critical: 'తీవ్రమైన హెచ్చరిక',
    readAloud: 'వినండి (వాయిస్)',
    stopReading: 'ఆపండి',
    downloadFhir: 'ABDM FHIR R4 డౌన్‌లోడ్ (JSON)',
    abhaLinked: 'ABHA లింక్ చేయబడింది & ధృవీకరించబడింది',
    routineCheck: 'సాధారణ పర్యవేక్షణ',
    consultDoctorSoon: 'త్వరలో డాక్టర్‌ను సంప్రదించండి',
    immediateCare: 'వెంటనే వైద్య సలహా తీసుకోండి',
    safetyDisclaimer: 'వైద్య నిరాకరణ: సేతు హెల్త్ AI అవగాహన కొరకు మాత్రమే. చికిత్స మార్చే ముందు మీ వైద్యుడిని సంప్రదించండి.',
  },
  ta: {
    appTitle: 'சேது ஹெல்த் AI கோபைலட்',
    appSubtitle: 'சிக்கலான மருத்துவ அறிக்கைகளை எளிய தமிழில் புரிந்து கொள்ளுங்கள்',
    tabOverview: 'டாஷ்போர்டு',
    tabUpload: 'அறிக்கை ஸ்கேன் & பகுப்பாய்வு',
    tabTimeline: 'சுகாதார காலவரிசை',
    tabTrends: 'உடல்நல போக்குகள்',
    tabMeds: 'மருந்து அட்டவணை',
    tabAbdm: 'ABDM / ABHA டிஜிட்டல் மையம்',
    tabArchitecture: 'கட்டமைப்பு',
    tabDeck: 'விளக்கக்காட்சி',
    uploadBtn: 'புதிய மருத்துவ அறிக்கையை பதிவேற்றவும்',
    trySampleBtn: 'மாதிரி அறிக்கையை முயற்சிக்கவும்',
    analyzingDoc: 'மருத்துவ அறிக்கை பகுப்பாய்வு செய்யப்படுகிறது...',
    plainSummaryTitle: 'எளிய மொழியில் உங்கள் ஆரோக்கிய சுருக்கம்',
    whyItMatters: 'இது உங்கள் ஆரோக்கியத்திற்கு ஏன் முக்கியம்',
    actionPlan: 'பரிந்துரைக்கப்பட்ட நடவடிக்கைகள்',
    dietTips: 'உணவு மற்றும் வாழ்க்கை முறை வழிகாட்டுதல்',
    questionsForDoctor: 'மருத்துவரிடம் கேட்க வேண்டிய கேள்விகள்',
    flaggedAbnormal: 'கவனிக்கப்பட வேண்டிய ஆய்வக முடிவுகள்',
    normal: 'இயல்பானது',
    elevated: 'அதிகம் (High)',
    low: 'குறைவு (Low)',
    critical: 'அவசர எச்சரிக்கை',
    readAloud: 'குரல் வழியே கேட்கவும்',
    stopReading: 'நிறுத்து',
    downloadFhir: 'ABDM FHIR R4 பதிவிறக்கம் (JSON)',
    abhaLinked: 'ABHA இணைக்கப்பட்டது',
    routineCheck: 'வழக்கமான கண்காணிப்பு',
    consultDoctorSoon: 'விரைவில் மருத்துவரை அணுகவும்',
    immediateCare: 'உடனடி மருத்துவ கவனிப்பு தேவை',
    safetyDisclaimer: 'மருத்துவ மறுப்பு: சேது ஹெல்த் AI ஒரு கல்வி உதவியாளர் மட்டுமே. மருத்துவரை அணுகி ஆலோசனை பெறவும்.',
  },
  bn: {
    appTitle: 'সেতু হেলথ এআই কোপাইলট',
    appSubtitle: 'জটিল মেডিকেল রিপোর্ট সহজ বাংলায় বুঝুন',
    tabOverview: 'ড্যাশবোর্ড',
    tabUpload: 'রিপোর্ট স্ক্যান ও বিশ্লেষণ',
    tabTimeline: 'স্বাস্থ্য টাইমলাইন',
    tabTrends: 'ভাইটাল ট্রেন্ডস',
    tabMeds: 'ওষুধের সময়সূচী',
    tabAbdm: 'আয়ুষ্মান ভারত (ABDM/ABHA)',
    tabArchitecture: 'সিস্টেম আর্কিটেকচার',
    tabDeck: 'প্রেজেন্টেশন স্লাইড',
    uploadBtn: 'নতুন মেডিকেল রিপোর্ট আপলোড করুন',
    trySampleBtn: 'নমুনা রিপোর্ট পরীক্ষা করুন',
    analyzingDoc: 'মেডিকেল রিপোর্ট বিশ্লেষণ করা হচ্ছে...',
    plainSummaryTitle: 'সহজ ভাষায় আপনার স্বাস্থ্য সারাংশ',
    whyItMatters: 'এটি আপনার স্বাস্থ্যের জন্য কেন গুরুত্বপূর্ণ',
    actionPlan: 'প্রস্তাবিত পদক্ষেপ',
    dietTips: 'খাবার এবং জীবনধারা নির্দেশিকা',
    questionsForDoctor: 'ডাক্তারকে জিজ্ঞাসা করার প্রশ্ন',
    flaggedAbnormal: 'চিহ্নিত ল্যাব টেস্ট ফলাফল',
    normal: 'স্বাভাবিক',
    elevated: 'বেশি (High)',
    low: 'কম (Low)',
    critical: 'জরুরি সতর্কতা',
    readAloud: 'পড়ে শোনান (ভয়েস)',
    stopReading: 'থামুন',
    downloadFhir: 'ABDM FHIR R4 ডাউনলোড (JSON)',
    abhaLinked: 'ABHA আইডি যাচাইকৃত',
    routineCheck: 'নিয়মিত পর্যবেক্ষণ',
    consultDoctorSoon: 'শীঘ্রই ডাক্তারের সাথে পরামর্শ করুন',
    immediateCare: 'অবিলম্বে চিকিৎসকের কাছে যান',
    safetyDisclaimer: 'চিকিৎসা দাবিত্যাগ: সেতু হেলথ এআই শুধুমাত্র সচেতনতার জন্য। চিকিৎসার জন্য সর্বদা চিকিৎসকের পরামর্শ নিন।',
  },
  mr: {
    appTitle: 'सेतू हेल्थ एआय कोपायलट',
    appSubtitle: 'वैद्यकीय अहवाल सोप्या मराठी भाषेत समजून घ्या',
    tabOverview: 'डॅशबोर्ड',
    tabUpload: 'अहवाल स्कॅन व विश्लेषण',
    tabTimeline: 'आरोग्य टाइमलाइन',
    tabTrends: 'व्हाइटल ट्रेंड्स',
    tabMeds: 'औषधांचे वेळापत्रक',
    tabAbdm: 'आयुष्मान भारत (ABDM/ABHA)',
    tabArchitecture: 'प्रणाली रचना',
    tabDeck: 'सादरीकरण स्लाईड्स',
    uploadBtn: 'नवीन वैद्यकीय अहवाल अपलोड करा',
    trySampleBtn: 'नमुना अहवाल तपासा',
    analyzingDoc: 'वैद्यकीय अहवाल तपासला जात आहे...',
    plainSummaryTitle: 'सोप्या भाषेत तुमचा आरोग्य सारांश',
    whyItMatters: 'हे तुमच्या आरोग्यासाठी का महत्त्वाचे आहे',
    actionPlan: 'शिफारस केलेल्या कृती',
    dietTips: 'आहार आणि जीवनशैली मार्गदर्शन',
    questionsForDoctor: 'डॉक्टरांना विचारावयाचे प्रश्न',
    flaggedAbnormal: 'लक्षात घेण्यासारखे लॅब निकाल',
    normal: 'सामान्य (Normal)',
    elevated: 'जास्त (High)',
    low: 'कमी (Low)',
    critical: 'गंभीर इशारा',
    readAloud: 'ऐका (आवाज)',
    stopReading: 'थांबवा',
    downloadFhir: 'ABDM FHIR R4 डाऊनलोड (JSON)',
    abhaLinked: 'ABHA आयडी पडताळणी पूर्ण',
    routineCheck: 'नियमित तपासणी',
    consultDoctorSoon: 'लवकरच डॉक्टरांचा सल्ला घ्या',
    immediateCare: 'तातडीने वैद्यकीय मदत घ्या',
    safetyDisclaimer: 'वैद्यकीय अस्वीकरण: सेतू हेल्थ एआय केवळ शैक्षणिक आणि मार्गदर्शनासाठी आहे. डॉक्टरांचा सल्ला घ्या.',
  },
  es: {
    appTitle: 'SetuHealth Copiloto de IA',
    appSubtitle: 'Traduciendo jerga médica a claridad humana',
    tabOverview: 'Panel General',
    tabUpload: 'Escanear y Analizar',
    tabTimeline: 'Línea de Tiempo de Salud',
    tabTrends: 'Tendencias Vitales',
    tabMeds: 'Horario de Medicamentos',
    tabAbdm: 'Centro Digital ABDM / FHIR',
    tabArchitecture: 'Arquitectura',
    tabDeck: 'Diapositivas',
    uploadBtn: 'Subir Nuevo Documento',
    trySampleBtn: 'Probar Documento de Muestra',
    analyzingDoc: 'Analizando informe médico con OCR y Visión...',
    plainSummaryTitle: 'Resumen de Salud en Lenguaje Sencillo',
    whyItMatters: 'Por qué esto importa para su salud',
    actionPlan: 'Pasos de Acción Recomendados',
    dietTips: 'Consejos de Estilo de Vida y Dieta',
    questionsForDoctor: 'Preguntas para su Médico',
    flaggedAbnormal: 'Biomarcadores Anormales Señalados',
    normal: 'Normal',
    elevated: 'Elevado (Alto)',
    low: 'Bajo',
    critical: 'Alerta Crítica',
    readAloud: 'Leer en Voz Alta (Audio)',
    stopReading: 'Detener',
    downloadFhir: 'Descargar ABDM FHIR R4 (JSON)',
    abhaLinked: 'Identificación Verificada',
    routineCheck: 'Monitoreo de Rutina',
    consultDoctorSoon: 'Consultar al Médico Pronto',
    immediateCare: 'Atención Médica Inmediata',
    safetyDisclaimer: 'Aviso médico: SetuHealth AI es una herramienta educativa e informativa. Consulte a su médico antes de alterar cualquier tratamiento.',
  }
};

/**
 * Speech synthesis helper
 */
export function speakText(text: string, langCode: LanguageCode, onEnd?: () => void): boolean {
  if (typeof window === 'undefined' || !('speechSynthesis' in window)) {
    return false;
  }

  window.speechSynthesis.cancel(); // Stop any active speech

  const utterance = new SpeechSynthesisUtterance(text);
  
  // Map language code to BCP-47 locale
  const langMap: Record<LanguageCode, string> = {
    en: 'en-IN',
    hi: 'hi-IN',
    te: 'te-IN',
    ta: 'ta-IN',
    bn: 'bn-IN',
    mr: 'mr-IN',
    es: 'es-ES'
  };

  utterance.lang = langMap[langCode] || 'en-IN';
  utterance.rate = 0.95; // Slightly slower for elderly comprehension
  utterance.pitch = 1.0;

  if (onEnd) {
    utterance.onend = onEnd;
    utterance.onerror = onEnd;
  }

  window.speechSynthesis.speak(utterance);
  return true;
}

export function stopSpeaking(): void {
  if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
    window.speechSynthesis.cancel();
  }
}
